### ISSUE TITLE
Using this theme brakes atom-ide-ui

### ISSUE THREAD

**Issue by caballerofelipe** [sonph/spacegray-light-neue-ui#6]
Hi, while using this theme and starting Atom, it brakes atom-ide-ui package and I get the following:
<img width="457" alt="screen shot 2018-08-22 at 12 12 09" src="https://user-images.githubusercontent.com/11650766/44472680-01cc1780-a605-11e8-9dbd-9c4bc353eb63.png">

It's an easy fix I guess... I edited manually the references file in atom-ide-ui but I guess you're missing the \@font-family definition.

**Comment by sonph** [comment]
Unfortunately I'm no longer using Atom, so this theme is more or less unmaintained. If you think that will fix it, please submit a pull request and I'll gladly merge it :)

**Comment by sonph** [comment]
On second thought, the uncompilable file is in `atom-ide-ui/modules/nuclide-commons-ui` and therefore unrelated to this theme. Even if it is, I imagine that `@font-family` should always be set by the user.
